### ISSUE TITLE
markdown support

### ISSUE THREAD

**Issue by salmanulfarzy** [sfarzy/learning_log#2]
Allow entry content to support markdown tags. There are several libraries for markdown. There are several criteria in choosing the library.

- python3 support
- still maintained
- production/stable condition
- healthy community
 
By comparing the available packages through [django packages](https://djangopackages.org/grids/g/markdown/), following libraries seemed viable

- [django-markdownx](https://github.com/adi-/django-markdownx) : Has a healthy community and been maintained for a while. Simple, suitable for power users.
- [django-markdown-app](https://github.com/sv0/django-markdown-app) : Not updated in the last 3 months. fork from klen's repo.
- [dracos-markdown-editor](https://github.com/agusmakmun/dracos-markdown-editor) : Relatively new comer. Full featured and provided a very nice interface. Not much community involvement. 
---

As of now, I would like to go with _django-markdownx_. It has healthy community. May change the library if it's not a good fit.

---
todo

- [x] enable markdown with live preview
- [x] remove text field
- [x] show rendered markdown in entries list

**Comment by salmanulfarzy** [comment]
Markdown support implemented using [django-markdownx](https://github.com/adi-/django-markdownx) with 332fc9558d6e285a61fda74dcd3803c9dc2593b2.

**Comment by sfarzy** [comment]
Show rendered markdown in list of entries 0e6117a5752f5a08430f8e8450490e40756202b6

**Comment by salmanulfarzy** [comment]
[dracos markdown](https://github.com/agusmakmun/dracos-markdown-editor) looks very promising. It provides

- Live preview
- Emoji support with cheat sheet
- Code hightlights
- Toolbar buttons
![](https://raw.githubusercontent.com/agusmakmun/dracos-markdown-editor/master/__screenshot/draceditor-preview.png)
